# Embedded file name: scripts/common/GroundEffectsSettings.py
from collections import namedtuple
MAX_DIST_TO_TERRAIN = 20

class MATERIAL:
    WATER = 'water'
    GROUND = 'ground'
    SAND = 'sand'
    ROCK = 'rock'
    SNOW = 'snow'
    GRASS = 'grass'


EXCLUDED_PLANES_WITH_2_ENGINES = ['me-p1102b, il-40, il-40p, mig-9, f7u, f90, f2h, gloster-javelin, attacker, westland-p-1056']
Effect = namedtuple('Effect', ['maxDistance',
 'airEffect',
 'groundParticle',
 'screenParticle'])
EFFECTS = {'40_el_hallouf_3': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                     MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                     MATERIAL.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
 '03_ocean': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
              MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
              MATERIAL.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand_yellow'),
              MATERIAL.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass')},
 '05_lighthouse': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                   MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                   MATERIAL.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                   MATERIAL.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
 '07_bay': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
            MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
            MATERIAL.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
            MATERIAL.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
 '08_asian_border': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                     MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                     MATERIAL.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                     MATERIAL.GROUND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_ground', screenParticle='screen_effect_ground'),
                     MATERIAL.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
 '09_arctic': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
               MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
               MATERIAL.SNOW: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_snow', screenParticle='screen_effect_snow')},
 '10_eastern_front': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                      MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                      MATERIAL.GROUND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_ground', screenParticle='screen_effect_ground'),
                      MATERIAL.SNOW: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_snow', screenParticle='screen_effect_snow')},
 '11_plateau': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand'),
                MATERIAL.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand'),
                MATERIAL.GROUND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand'),
                MATERIAL.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
 '12_fjords': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
               MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
               MATERIAL.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
               MATERIAL.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
 '13_harbor': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
               MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
               MATERIAL.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
               MATERIAL.GROUND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_ground', screenParticle='screen_effect_ground'),
               MATERIAL.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
 '14_adriatic': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                 MATERIAL.GROUND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_ground', screenParticle='screen_effect_ground'),
                 MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                 MATERIAL.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand'),
                 MATERIAL.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass')},
 '16_fortress': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                 MATERIAL.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                 MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                 MATERIAL.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
 '17_winter_war': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water_dark', screenParticle=''),
                   MATERIAL.SNOW: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_snow_dark', screenParticle='screen_effects_snow_dark')},
 '18_convoy': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
               MATERIAL.SNOW: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_snow', screenParticle='screen_effect_snow')},
 '20_canyon_': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                MATERIAL.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                MATERIAL.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
 '26_national_park_2': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                        MATERIAL.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                        MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                        MATERIAL.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
 '23_province': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                 MATERIAL.GROUND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_ground', screenParticle='screen_effect_ground'),
                 MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                 MATERIAL.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                 MATERIAL.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
 '24_observatory': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                    MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                    MATERIAL.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                    MATERIAL.SNOW: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_snow', screenParticle='screen_effect_snow')},
 '26_national_park_2': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                        MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                        MATERIAL.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                        MATERIAL.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
 '27_giant_dam': {MATERIAL.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                  MATERIAL.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                  MATERIAL.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                  MATERIAL.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')}}