# Embedded file name: scripts/common/OperationCodes.py
import string
CMD_QA_FIRST_ID = 500
CMD_QA_LAST_ID = 600
REQUEST_ID_UNRESERVED_MAX = 1000000000
REQUEST_ID_UNRESERVED_MIN = 0

class OPERATION_CODE:
    """
    Operation codes enum
    """
    CAPTCHA_CHALLENGE = 0
    CAPTCHA_GET_DATA = 1
    AOGAS_GET_INFO = 2
    TUTORIAL_ACTION = 3
    TUTORIAL_START_LESSON = 4
    TUTORIAL_REQUEST_FINISH_LESSON = 5
    TUTORIAL_FINISH_LESSON = 6
    TUTORIAL_LESSON_PART = 7
    TUTORIAL_EXECUTE_ACTION_SEQUENCE = 8
    TUTORIAL_RESPAWN_DONE = 9
    TUTORIAL_GET_POSITION = 10
    TUTORIAL_LESSON_PART_RESTART = 11
    TUTORIAL_START_LESSON_REAL = 12
    TUTORIAL_SET_WPS_SPLINE = 13
    TUTORIAL_SET_WPS_EVASION = 14
    TUTORIAL_SET_BS_SIMPLE_MODE = 15
    TUTORIAL_RESTART_PART = 16
    TUTORIAL_PAUSE = 17
    TUTORIAL_RELOAD_SHELLS = 18
    PVE_SCENE_TYPE = 50
    PVE_BOTS_SPAWN_MESSAGE = 51
    PVE_MESSAGE = 52
    PVE_LOOSE = 53
    PVE_WIN = 54
    CMD_SELL_EQUIPMENT = 219
    CMD_BUY_SHELL = 220
    CMD_SELL_SHELL = 221
    CMD_GET_TRAINING_ROOM_FILTERS = 233
    CMD_TRAINING_REFRESH_ROOM_LIST = 234
    CMD_TRAINING_ON_ENTER_ROOM = 235
    CMD_GET_TRAINING_CREATE_ROOM_FILTERS = 236
    CMD_TRAINING_ROOM_CREATED = 237
    CMD_TRAINING_ENTER_ROOM_GET_INIT_DATA = 238
    CMD_TRAINING_UPDATE_ACCOUNT_TEAM_ID = 239
    CMD_TRAINING_ROOM_LEAVE = 240
    CMD_SHOW_TRAINING_ROOM_RESPONSE = 241
    CMD_TRAINING_ADD_BOTS = 242
    CMD_TRAINING_DELETE_BOT = 243
    CMD_TRAINING_BOTS_AUTO_FILL = 244
    CMD_TRAINING_CHANGE_MAP = 245
    CMD_TRAINING_CHANGE_DESC = 246
    CMD_TRAINING_BOTS_REMOVE = 247
    CMD_TRAINING_SWAP_TEAMS = 248
    CMD_TRAINING_MOVE_TEAM = 249
    CMD_SUBSCRIBE_ROOM_LIST = 250
    CMD_UNSUBSCRIBE_ROOM_LIST = 251
    CMD_INSTALL_PRESSET = 252
    CMD_TRAINING_EDIT_BOT = 253
    CMD_TREE_AIRCRAFT_RESEARCH = 261
    CMD_RESEARCH_UPGRADE = 262
    CMD_BUY_UPGRADE = 263
    CMD_GET_AIRCRAFT_EXP = 270
    CMD_CLEAR_INVENTORY = 283
    CMD_SAVE_CUSTOM_PRESET = 284
    CMD_DEBUG_BREAK_ALL_PLANES = 290
    CMD_DEBUG_REPAIR_ALL_PLANES = 291
    CMD_DEBUG_QUEST_CHANGE_PROGRESS = 292
    CMD_DEBUG_QUEST_SET_COMPLETE = 293
    CMD_DEBUG_QUEST_SEND_MESSAGE = 294
    CMD_DEBUG_QUEST_DROP_PROGRESS = 295
    CMD_DEBUG_QUEST_RESET_DAILY = 296
    CMD_HANGAR_SET_SLOT_PRIMARY = 300
    CMD_HANGAR_UPDATE_PLAYER_RESOURCES = 301
    CMD_HANGAR_SET_AIRPLANE_AUTO_REPAIR_FLAG = 303
    CMD_HANGAR_GET_TUTORIAL_INFO = 304
    CMD_HANGAR_GET_CUSTOMIZATION_LIST = 305
    CMD_HANGAR_BUY_PREMIUM = 307
    CMD_HANGAR_BUY_CREDITS = 308
    CMD_HANGAR_BUY_FREE_EXP = 309
    CMD_HANGAR_SET_TUTORIAL_INVITES = 310
    CMD_HANGAR_GET_TUTORIAL_FORBID_INFO = 311
    CMD_MAINTENANCE_SET_SHELLS_AUTO_REFILLING_FLAG = 602
    CMD_GET_INTERFACE_DATA = 603
    CMD_GET_NEW_SESSION_KEY = 604
    CMD_SAVE_SESSION_KEY = 605
    CMD_SESSION_KEY_SYNCED = 606
    CMD_GET_IFACE_DATA = 610
    CMD_SET_IFACE_DATA = 611
    CMD_SEND_LAST_SESSION = 615
    CMD_ACTION_LIST_CHANGED = 616
    CMD_SEND_INTERVIEW_ANSWER = 650
    CMD_VOIP_GET_INIT_DATA = 700
    QA_RESET_DATA = 500
    QA_SET = 501
    QA_GET = 502
    QA_CREATE_ARENA = 503
    QA_JOIN_ARENA = 504
    QA_CLEAR_POOL = 505
    QA_GET_POOL = 506
    QA_ADD_ACCOUNT_TO_QUEUE = 507
    QA_ADD_RANDOM_ACCOUNTS_TO_QUEUE = 520
    QA_GET_WAIT_LISTS_FROM_ARENA_MANAGER = 521
    QA_SET_FAKE_ONLINE_PLAYERS_ON_ARENA_MANAGER = 522
    QA_CLEAR_BALANCER_DATA = 523
    QA_GET_BALANCED_LIST = 508
    QA_SET_BALANCER_FAKE_ONLINE_PLAYERS = 509
    QA_SET_BASEAPP_DATA = 510
    QA_GET_BASEAPP_DATA = 511
    QA_SET_ACCOUNT_TYPE = 512
    QA_TEST_START_NOTIFICATION = 513
    QA_TEST_FINISH_NOTIFICATION = 514
    QA_SERVER_PRINT = 515
    QA_ADD_SQUAD_TO_QUEUE = 516
    QA_NEW_BALANCER_CREATE_BALANCER = 530
    QA_NEW_BALANCER_ADD_ACCOUNTS_TO_QUEUE = 531
    QA_NEW_BALANCER_FLUSH_QUEUE = 533
    QA_NEW_BALANCER_ADD_SINGLE_PLAYER = 534
    QA_NEW_BALANCER_ADD_SQUAD = 535
    CMD_MAX_OPERATION_CODE = 1024


class OPERATION_RETURN_CODE:
    """
    Operation return code enum
    """
    FAILED = -1
    WRONG_ARGS = -2
    SUCCESS = 0
    SYNC_WAIT = 1
    WGM_DISABLE = 2
    FAILURE_WRONG_TRANSACTION_TYPE = 10
    FAILURE_NO_FREE_SLOT = 11
    FAILURE_NO_ENOUGH_CREDITS = 12
    FAILURE_NO_ENOUGH_GOLD = 13
    FAILURE_ENGINE_NOT_FOUND = 14
    FAILURE_RADIO_NOT_FOUND = 15
    FAILURE_SHELL_NOT_FOUND = 16
    FAILURE_NOT_ENOUGH_EXP = 17
    FAILURE_NO_ENOUGH_EXPERIENCE = 18
    FAILURE_NO_ENOUGH_PLANEEXPERIENCE = 19
    FAILURE_PARENT_UPGRADE_NOT_OPENED = 20
    FAILURE_UPGRADE_NOT_OPENED = 21
    FAILURE_NOT_ENOUGH_UPGRADES = 22
    FAILURE_UPGRADE_ALREADY_OPENED = 23
    FAILURE_WEAPON_ALREADY_INSTALLED = 24
    FAILURE_WEAPON_SLOT_UNAVAILABLE = 25
    FAILURE_NOT_ENOUGH_WEAPON = 26
    FAILURE_REQUIRED_UPGRADE_NOT_INSTALLED = 27
    FAILURE_NOT_FOUND_APPROPRIATE_WEAPONS = 28
    FAILURE_GOLD_ADD_ONLY = 29
    FAILURE_MAX_SOLD_PLANES_PER_DAY_REACHED = 30
    FAILURE_NO_ENOUGH_TICKETS = 31
    FAILURE_GOLD_PRICE_NOT_SUPPORTED = 32
    START_EXAM = 50
    RESTART_LESSON = 51
    NEXT_LESSON = 52
    FAILURE_WRONG_JOIN_CONTEXT = 101
    FAILURE_WRONG_ITEM_TYPE = 102
    FAILURE_WRONG_IDTYPELIST_SIZE = 103
    FAILURE_KWARG_NOT_FOUND = 104
    FAILURE_WRONG_COUNT = 105
    FAILURE_PRICE_SCHEME_NOT_FOUND = 106
    FAILURE_OPERATION_FORBIDDEN = 107
    FAILURE_UNSUPPORTED_OPERATION = 108
    FAILURE_SELL_UNAVAILABLE = 109
    FAILURE_OPERATION_FINANCE_LIMIT_EXCEEDED = 110
    FAILURE_TRANSACTION_FINANCE_LIMIT_EXCEEDED = 111
    FAILURE_WRONG_KWARG_TYPE = 112
    FAILURE_BUY_UNAVAILABLE = 113
    FAILURE_CREWMEMBER_NOT_FOUND = 201
    FAILURE_WRONG_SKILL_LEVEL = 202
    FAILURE_SPECIALIZATION_INCOMPATIBLE = 203
    FAILURE_CREWMEMBER_LOST_FROM_PLANE = 204
    FAILURE_SPECIALIZATION_LOST_FROM_PLANE = 205
    FAILURE_NO_PLACE_IN_PLANE = 206
    FAILURE_CREWMEMBER_ALREADY_IN_BARRACK = 207
    FAILURE_CREW_LOCKED = 208
    FAILURE_BARRACK_FULL = 209
    FAILURE_WRONG_DROP_LEVEL = 210
    FAILURE_NO_SKILLS_TO_DROP = 211
    FAILURE_CREWMEMBER_ALREADY_USED = 212
    FAILURE_NATION_INCOMPATIBLE = 213
    FAILURE_SKILL_ALREADY_LEARNED = 214
    FAILURE_SKILL_INCOMPATIBLE = 215
    FAILURE_NOT_ENOUGH_SKILLS = 216
    FAILURE_SPECIALIZATION_NOT_LEARNED = 217
    FAILURE_SKILL_LIST = 218
    FAILURE_SKILL_LEVEL_LESS_THAN_CURRENT = 219
    FAILURE_CREWMEMBER_ALREADY_KNOWS_PLANE = 220
    FAILURE_SKILL_NOT_FOUND = 221
    FAILURE_NOT_ENOUGH_FREE_SP = 222
    FAILURE_DEPENDED_SKILL_NOT_LEARNED = 223
    FAILURE_DROP_SKILL_NO_VALID_COST = 224
    FAILURE_WRONG_EXP_LEVEL = 225
    FAILURE_WRONG_UNIQUE_INDEX = 226
    FAILURE_UNIQUE_CREW_EXISTS = 227
    FAILURE_WRONG_SWAP_TO_EMPTY_SLOT = 228
    FAILURE_WRONG_GLOBAL_ID = 301
    FAILURE_WRONG_WEAPONSLOT = 302
    FAILURE_WEAPONSLOT_EMPTY = 303
    FAILURE_PLANE_NOT_BOUGHT = 304
    FAILURE_PLANE_IS_IN_BATTLE = 305
    FAILURE_WRONG_PLANE = 306
    FAILURE_PLANE_ALREADY_BOUGHT = 307
    FAILURE_PLANE_NOT_FOUND = 308
    FAILURE_PLANE_LOCKED = 309
    FAILURE_PLANE_NOT_OPENED = 310
    FAILURE_BELT_NOT_FOUND = 401
    FAILURE_CANNOT_BUY_FREE_BELTS = 402
    FAILURE_UNEXPECTED_BELT = 403
    FAILURE_GUN_NOT_FOUND = 404
    FAILURE_BELT_INCOMPATIBLE = 405
    FAILURE_NOT_ENOUGH_BELTS = 406
    FAILURE_CANNOT_SELL_FREE_BELTS = 407
    FAILURE_CAMOUFLAGE_NOT_FOUND = 501
    FAILURE_CAMOUFLAGE_PERMANENTLY_BOUGHT = 502
    FAILURE_WRONG_EXPIRATION_TIME = 503
    FAILURE_CAMOUFLAGE_LOCKED = 504
    FAILURE_WRONG_ARENA_TYPE = 505
    FAILURE_CAMOUFLAGE_NOT_BOUGHT = 506
    FAILURE_CAMOUFLAGE_EXPIRED = 507
    FAILURE_CAMOUFLAGE_ADD_DEFAULT = 508
    FAILURE_CONSUMABLE_NOT_FOUND = 601
    FAILURE_NOT_ENOUGH_CONSUMABLES = 602
    FAILURE_CONSUMABLE_NOT_INSTALLED = 603
    FAILURE_WRONG_CONSUMABLE_SLOT = 604
    FAILURE_CONSUMABLE_INCOMPATIBLE = 605
    FAILURE_CONSUMABLE_SLOT_ALREADY_USED = 606
    FAILURE_CONSUMABLE_ALREADY_INSTALLED = 607
    FAILURE_CONSUMABLE_GROUP_ALREADY_INSTALLED = 608
    FAILURE_EQUIPMENT_NOT_FOUND = 701
    FAILURE_NOT_ENOUGH_EQUIPMENT = 702
    FAILURE_EQUIPMENT_NOT_INSTALLED = 703
    FAILURE_EQUIPMENT_INCOMPATIBLE = 704
    FAILURE_EQUIPMENT_SLOT_ALREADY_USED = 705
    FAILURE_EQUIPMENT_ALREADY_INSTALLED = 706
    FAILURE_WRONG_EQUIPMENT_SLOT = 707
    FAILURE_CANNOT_DESTROY_SIMPLE_EQUIPMENT = 708
    FAILURE_WEAPON_NOT_FOUND = 801
    FAILURE_UPGRADE_NOT_FOUND = 802
    FAILURE_SHELL_INCOMPATIBLE = 803
    FAILURE_NOT_ENOUGH_SHELLS_ON_PLANE = 804
    FAILURE_SHELLS_ALREADY_INSTALLED = 805
    FAILURE_UNKNOWN_CURRENCY = 901
    FAILURE_CURRENCY_UNAVAILABLE = 902
    FAILURE_UNKNOWN_PACK_ID = 1000
    FAILURE_DISABLE_PACK_ID = 1001


_OPERATION_RETURN_CODE_DESCRIPTIONS = {OPERATION_RETURN_CODE.SUCCESS: 'OK',
 OPERATION_RETURN_CODE.WGM_DISABLE: 'WGM is disabled',
 OPERATION_RETURN_CODE.FAILED: 'Unknown error',
 OPERATION_RETURN_CODE.FAILURE_WRONG_TRANSACTION_TYPE: 'not allow use gold {gold} or/and freeExp {experience} for this transaction type',
 OPERATION_RETURN_CODE.FAILURE_WRONG_JOIN_CONTEXT: 'Operation called from wrong context: {joinCtx}',
 OPERATION_RETURN_CODE.FAILURE_WRONG_ITEM_TYPE: "Wrong item type supplied, expected '{expected}', got '{got}'",
 OPERATION_RETURN_CODE.FAILURE_WRONG_KWARG_TYPE: "Wrong '{name}' kward type supplied, expected '{expected}', got '{got}'",
 OPERATION_RETURN_CODE.FAILURE_WRONG_IDTYPELIST_SIZE: 'idTypeList has invalid length - expected {expected}, got {got}: {idTypeList}',
 OPERATION_RETURN_CODE.FAILURE_KWARG_NOT_FOUND: "'{name}' not found in kwargs: {kwargs}",
 OPERATION_RETURN_CODE.FAILURE_WRONG_COUNT: 'Wrong count passed: {count}',
 OPERATION_RETURN_CODE.FAILURE_BUY_UNAVAILABLE: 'Buy unavailable for {obType} (id={obID})',
 OPERATION_RETURN_CODE.FAILURE_PRICE_SCHEME_NOT_FOUND: 'Price scheme not found for {obType} (id={obID})',
 OPERATION_RETURN_CODE.FAILURE_OPERATION_FORBIDDEN: 'Operation forbidden',
 OPERATION_RETURN_CODE.FAILURE_UNSUPPORTED_OPERATION: 'Unsupported operation',
 OPERATION_RETURN_CODE.FAILURE_SELL_UNAVAILABLE: 'Sell unavailable for {obType} (id={obID})',
 OPERATION_RETURN_CODE.FAILURE_OPERATION_FINANCE_LIMIT_EXCEEDED: 'Operation finance limit exceeded for {financeType}: {amount}',
 OPERATION_RETURN_CODE.FAILURE_TRANSACTION_FINANCE_LIMIT_EXCEEDED: 'Operation finance limit exceeded for {financeType}: {amount}',
 OPERATION_RETURN_CODE.FAILURE_NO_ENOUGH_CREDITS: 'Not enough credits',
 OPERATION_RETURN_CODE.FAILURE_NO_ENOUGH_GOLD: 'Not enough gold',
 OPERATION_RETURN_CODE.FAILURE_NO_ENOUGH_EXPERIENCE: 'Not enough experience',
 OPERATION_RETURN_CODE.FAILURE_NO_ENOUGH_TICKETS: 'Not enough tickets',
 OPERATION_RETURN_CODE.FAILURE_GOLD_ADD_ONLY: 'Wallet is closed',
 OPERATION_RETURN_CODE.FAILURE_NO_FREE_SLOT: 'No free hangar slot present',
 OPERATION_RETURN_CODE.FAILURE_CREWMEMBER_NOT_FOUND: 'Crewmember (id={memberID}) not found in barrack',
 OPERATION_RETURN_CODE.FAILURE_WRONG_SKILL_LEVEL: 'Wrong skill level passed: {skillLevel}',
 OPERATION_RETURN_CODE.FAILURE_SPECIALIZATION_INCOMPATIBLE: 'Specialization (id={specializationID}) is incompatible with plane (id={planeID})',
 OPERATION_RETURN_CODE.FAILURE_CREWMEMBER_LOST_FROM_PLANE: 'PData for plane (id={planeID}) is corrupted: crewmember (id={memberID}) lost from plane',
 OPERATION_RETURN_CODE.FAILURE_SPECIALIZATION_LOST_FROM_PLANE: 'PData for plane (id={planeID}) is corrupted: specialization (id={specializationID}) lost from plane',
 OPERATION_RETURN_CODE.FAILURE_NO_PLACE_IN_PLANE: 'Plane (id={planeID}) already has crewmember with specialization (id={specializationID})',
 OPERATION_RETURN_CODE.FAILURE_CREWMEMBER_ALREADY_IN_BARRACK: 'Crewmember (id={memberID}) already in barrack',
 OPERATION_RETURN_CODE.FAILURE_CREW_LOCKED: 'Plane (id={planeID}) is locked for crew manipulations',
 OPERATION_RETURN_CODE.FAILURE_BARRACK_FULL: 'No free place in barrack',
 OPERATION_RETURN_CODE.FAILURE_WRONG_DROP_LEVEL: 'Wrong drop level passed: {dropLevel}',
 OPERATION_RETURN_CODE.FAILURE_NO_SKILLS_TO_DROP: 'Crewmember (id={memberID}) has no skills to drop',
 OPERATION_RETURN_CODE.FAILURE_CREWMEMBER_ALREADY_USED: 'Crewmember (id={memberID}) is already used on another plane (id={planeID})',
 OPERATION_RETURN_CODE.FAILURE_NATION_INCOMPATIBLE: "Crewmember's (id={memberID}) nation is incompatible with plane (id={planeID})",
 OPERATION_RETURN_CODE.FAILURE_SKILL_ALREADY_LEARNED: 'Crewmember (id={memberID}) already learned skill (id={skillID})',
 OPERATION_RETURN_CODE.FAILURE_SKILL_INCOMPATIBLE: 'Skill (id={skillID}) is incompatible with crewmember (id={memberID})',
 OPERATION_RETURN_CODE.FAILURE_NOT_ENOUGH_SKILLS: 'Skill (id={skillID}) requires {required} skills to be learned, {got} got',
 OPERATION_RETURN_CODE.FAILURE_SPECIALIZATION_NOT_LEARNED: 'Crewmember (id={memberID}) has not learned specialization to learn new skills',
 OPERATION_RETURN_CODE.FAILURE_DEPENDED_SKILL_NOT_LEARNED: 'Crewmember (id={memberID}) has not learned depended skill to learn new skills',
 OPERATION_RETURN_CODE.FAILURE_NOT_ENOUGH_FREE_SP: 'Crewmember (id={memberID}) has not enough free SP learn new skills',
 OPERATION_RETURN_CODE.FAILURE_SKILL_LEVEL_LESS_THAN_CURRENT: 'SkillLevel passed {skillLevel} is less than current {current}',
 OPERATION_RETURN_CODE.FAILURE_CREWMEMBER_ALREADY_KNOWS_PLANE: 'Crewmember (id={memberID}) already specialized on plane (id={planeID})',
 OPERATION_RETURN_CODE.FAILURE_SKILL_LIST: 'Wrong skills list  (id={skillID}) has duplicates',
 OPERATION_RETURN_CODE.FAILURE_SKILL_NOT_FOUND: 'Skill (id={skillID}) not found in db',
 OPERATION_RETURN_CODE.FAILURE_DROP_SKILL_NO_VALID_COST: 'Wrong cost for drop skill (cost: {costCredits}:{costGold} spend {spendCredits}:{spendGold})',
 OPERATION_RETURN_CODE.FAILURE_WRONG_EXP_LEVEL: 'Wrong exp cost {addedExp} for exp to sp exchange. Crewmember (id={memberID}) left exp for sp {leftExpForSP}',
 OPERATION_RETURN_CODE.FAILURE_WRONG_UNIQUE_INDEX: 'Wrong unique index for crew {uniqueID}',
 OPERATION_RETURN_CODE.FAILURE_UNIQUE_CREW_EXISTS: 'Unique crew exists {uniqueID}',
 OPERATION_RETURN_CODE.FAILURE_WRONG_SWAP_TO_EMPTY_SLOT: 'Swap to empty plane (id={planeID}) crewmember (id={memberID}). Use install insted',
 OPERATION_RETURN_CODE.FAILURE_PLANE_ALREADY_BOUGHT: 'Plane {planeID} already bought',
 OPERATION_RETURN_CODE.FAILURE_PLANE_NOT_FOUND: 'Plane {planeID} not found in db',
 OPERATION_RETURN_CODE.FAILURE_PLANE_LOCKED: 'Plane {planeID} is locked, block type: {blockType}',
 OPERATION_RETURN_CODE.FAILURE_PLANE_NOT_OPENED: 'Plane {planeID} is not opened yet',
 OPERATION_RETURN_CODE.FAILURE_WRONG_GLOBAL_ID: 'PData for plane {planeID} is corrupted: wrong globalID: {globalID}',
 OPERATION_RETURN_CODE.FAILURE_WRONG_WEAPONSLOT: 'Weapon configuration not found for weaponslot {slotID} on plane {planeID}',
 OPERATION_RETURN_CODE.FAILURE_WEAPONSLOT_EMPTY: 'Weaponslot {slotID} not installed or empty on plane {planeID}',
 OPERATION_RETURN_CODE.FAILURE_PLANE_NOT_BOUGHT: 'Plane {planeID} not found un pdata',
 OPERATION_RETURN_CODE.FAILURE_PLANE_IS_IN_BATTLE: 'Plane {planeID} is in battle',
 OPERATION_RETURN_CODE.FAILURE_WRONG_PLANE: 'Plane {planeID} not allowed to player',
 OPERATION_RETURN_CODE.FAILURE_BELT_NOT_FOUND: 'Ammobelt (id={beltID}) not found in db',
 OPERATION_RETURN_CODE.FAILURE_CANNOT_BUY_FREE_BELTS: 'Cannot buy free belts (id={beltID})',
 OPERATION_RETURN_CODE.FAILURE_CANNOT_SELL_FREE_BELTS: 'Cannot sell free belts (id={beltID})',
 OPERATION_RETURN_CODE.FAILURE_UNEXPECTED_BELT: 'Unexpected beltID passed, expected {expected}, got {got}',
 OPERATION_RETURN_CODE.FAILURE_GUN_NOT_FOUND: 'Gun (name={name}) not found in db',
 OPERATION_RETURN_CODE.FAILURE_BELT_INCOMPATIBLE: 'Belt (id={beltID}) is not compatible with gun (name={gunName}) on plane (id={planeID})',
 OPERATION_RETURN_CODE.FAILURE_NOT_ENOUGH_BELTS: 'Not enough belts (id={beltID}) in depot',
 OPERATION_RETURN_CODE.FAILURE_CAMOUFLAGE_NOT_FOUND: 'Camouflage (id={camouflageID}) not found in db',
 OPERATION_RETURN_CODE.FAILURE_CAMOUFLAGE_PERMANENTLY_BOUGHT: 'Camouflage (id={camouflageID}) is permanently bought',
 OPERATION_RETURN_CODE.FAILURE_WRONG_EXPIRATION_TIME: 'Wrong expiration time passed: {expirationTime}',
 OPERATION_RETURN_CODE.FAILURE_CAMOUFLAGE_LOCKED: 'Camouflage {camouflageID} is locked',
 OPERATION_RETURN_CODE.FAILURE_WRONG_ARENA_TYPE: 'Wrong arena type passed: {arenaType}',
 OPERATION_RETURN_CODE.FAILURE_CAMOUFLAGE_NOT_BOUGHT: 'Camouflage (id={camouflageID}) is not bought',
 OPERATION_RETURN_CODE.FAILURE_CAMOUFLAGE_EXPIRED: 'Camouflage (id={camouflageID}) expired',
 OPERATION_RETURN_CODE.FAILURE_CAMOUFLAGE_ADD_DEFAULT: 'Camouflage (id={camouflageID}) can not add another default',
 OPERATION_RETURN_CODE.FAILURE_CONSUMABLE_NOT_FOUND: 'Consumable (id={consumableID}) not found in db',
 OPERATION_RETURN_CODE.FAILURE_NOT_ENOUGH_CONSUMABLES: 'Not enough consumables (id={consumableID}) in depot',
 OPERATION_RETURN_CODE.FAILURE_CONSUMABLE_NOT_INSTALLED: 'Consumable (id={consumableID}) not installed on plane (id={planeID})',
 OPERATION_RETURN_CODE.FAILURE_WRONG_CONSUMABLE_SLOT: 'Wrong slot index: {slotIndex}',
 OPERATION_RETURN_CODE.FAILURE_CONSUMABLE_INCOMPATIBLE: 'Consumable (id={consumableID}) is not compatible with plane (id={planeID})',
 OPERATION_RETURN_CODE.FAILURE_CONSUMABLE_SLOT_ALREADY_USED: 'Slot {slotIndex} is already used on plane (id={planeID})',
 OPERATION_RETURN_CODE.FAILURE_CONSUMABLE_ALREADY_INSTALLED: 'Consumable (id={consumableID}) already installed on plane (id={planeID})',
 OPERATION_RETURN_CODE.FAILURE_CONSUMABLE_GROUP_ALREADY_INSTALLED: 'Consumable from same group with (id={consumableID}) already installed on plane (id={planeID})',
 OPERATION_RETURN_CODE.FAILURE_EQUIPMENT_NOT_FOUND: 'Equipment (id={equipmentID}) not found in db',
 OPERATION_RETURN_CODE.FAILURE_NOT_ENOUGH_EQUIPMENT: 'Not enough equipment (id={equipmentID}) in depot',
 OPERATION_RETURN_CODE.FAILURE_EQUIPMENT_NOT_INSTALLED: 'Equipment (id={equipmentID}) not installed on plane (id={planeID})',
 OPERATION_RETURN_CODE.FAILURE_EQUIPMENT_INCOMPATIBLE: 'Equipment (id={equipmentID}) is not compatible with plane (id={planeID})',
 OPERATION_RETURN_CODE.FAILURE_EQUIPMENT_SLOT_ALREADY_USED: 'Slot {slotIndex} is already used on plane (id={planeID})',
 OPERATION_RETURN_CODE.FAILURE_EQUIPMENT_ALREADY_INSTALLED: 'Equipment (id={equipmentID}) already installed on plane (id={planeID})',
 OPERATION_RETURN_CODE.FAILURE_WRONG_EQUIPMENT_SLOT: 'Wrong slot index: {slotIndex}',
 OPERATION_RETURN_CODE.FAILURE_CANNOT_DESTROY_SIMPLE_EQUIPMENT: 'Cannot destroy simple equipment (id={equipmentID})',
 OPERATION_RETURN_CODE.FAILURE_WEAPON_NOT_FOUND: 'Weapon (id={weaponID}) not found',
 OPERATION_RETURN_CODE.FAILURE_UPGRADE_NOT_FOUND: 'Upgrade (name={upgradeName}) not found',
 OPERATION_RETURN_CODE.FAILURE_UPGRADE_NOT_OPENED: 'Upgrade (id={upgradeID}) not opened',
 OPERATION_RETURN_CODE.FAILURE_NOT_ENOUGH_UPGRADES: 'Not enough upgrades (id={upgradeID}) in depot',
 OPERATION_RETURN_CODE.FAILURE_SHELL_INCOMPATIBLE: 'Weapon ({shellType}, id={shellID}) is incompatible with weaponslot {slotID}',
 OPERATION_RETURN_CODE.FAILURE_NOT_ENOUGH_SHELLS_ON_PLANE: 'Not enough shells (shellType, id={shellID}) on plane (id={planeID})',
 OPERATION_RETURN_CODE.FAILURE_SHELLS_ALREADY_INSTALLED: 'Shells ({shellType}, id={shellID}) already installed on plane ((id={planeID})',
 OPERATION_RETURN_CODE.FAILURE_UNKNOWN_CURRENCY: 'Unknown currency = {currency}',
 OPERATION_RETURN_CODE.FAILURE_CURRENCY_UNAVAILABLE: 'Unavailable currency = {currency}',
 OPERATION_RETURN_CODE.FAILURE_UNKNOWN_PACK_ID: 'Unkown packID = {packID}',
 OPERATION_RETURN_CODE.FAILURE_DISABLE_PACK_ID: 'Disable packID = {packID}'}

class SafeFormatter(string.Formatter):

    def __init__(self, enableWarnings):
        super(SafeFormatter, self).__init__()
        self.__enableWarnings = enableWarnings

    def get_value(self, key, args, kwargs):
        try:
            return super(SafeFormatter, self).get_value(key, args, kwargs)
        except (IndexError, KeyError):
            if self.__enableWarnings:
                from debug_utils import LOG_WARNING
                LOG_WARNING("Format warning: value for key '{0}' not found, empty string used".format(key))
            return ''


def getCodeDescription(operationReturnCode, enableWarnings, **kwargs):
    formatter = SafeFormatter(enableWarnings)
    return formatter.format(_OPERATION_RETURN_CODE_DESCRIPTIONS.get(operationReturnCode, 'Unknown error'), **kwargs)