# Embedded file name: scripts/client/_packs_db.py


class Dummy:
    pass


isServerDatabase = True
Packs = Dummy()
Packs.packs = {1: {'name': 'FRANCE_LTO',
     'items': [{'type': 'add',
                'idTypeList': [[7592, 'plane']],
                'count': 1,
                'related': [{'type': 'gift',
                             'idTypeList': [[None, 'crewmember'], [7592, 'plane']],
                             'count': 1},
                            {'type': 'gift',
                             'idTypeList': [[None, 'crewmember'], [7592, 'plane']],
                             'count': 1},
                            {'type': 'gift',
                             'idTypeList': [[-1525161382, 'camouflage']],
                             'count': 1,
                             'related': [{'type': 'install',
                                          'idTypeList': [[-1525161382, 'camouflage']]},
                                         {'type': 'install',
                                          'idTypeList': [[-1525161382, 'camouflage']]},
                                         {'type': 'install',
                                          'idTypeList': [[-1525161382, 'camouflage']]},
                                         {'type': 'install',
                                          'idTypeList': [[-1525161382, 'camouflage']]}]},
                            {'type': 'gift',
                             'idTypeList': [[1346636910, 'camouflage']],
                             'count': 1,
                             'related': [{'type': 'install',
                                          'idTypeList': [[1346636910, 'camouflage']]}]},
                            {'type': 'gift',
                             'idTypeList': [[-629067880, 'camouflage']],
                             'count': 1,
                             'related': [{'type': 'install',
                                          'idTypeList': [[-629067880, 'camouflage']]}]}]}, {'type': 'add',
                'idTypeList': [[7591, 'plane']],
                'count': 1,
                'related': [{'type': 'gift',
                             'idTypeList': [[None, 'crewmember'], [7591, 'plane']],
                             'count': 1},
                            {'type': 'gift',
                             'idTypeList': [[None, 'crewmember'], [7591, 'plane']],
                             'count': 1},
                            {'type': 'gift',
                             'idTypeList': [[-1214100044, 'camouflage']],
                             'count': 1,
                             'related': [{'type': 'install',
                                          'idTypeList': [[-1214100044, 'camouflage']]},
                                         {'type': 'install',
                                          'idTypeList': [[-1214100044, 'camouflage']]},
                                         {'type': 'install',
                                          'idTypeList': [[-1214100044, 'camouflage']]},
                                         {'type': 'install',
                                          'idTypeList': [[-1214100044, 'camouflage']]}]},
                            {'type': 'gift',
                             'idTypeList': [[1123132288, 'camouflage']],
                             'count': 1,
                             'related': [{'type': 'install',
                                          'idTypeList': [[1123132288, 'camouflage']]}]},
                            {'type': 'gift',
                             'idTypeList': [[-1658759864, 'camouflage']],
                             'count': 1,
                             'related': [{'type': 'install',
                                          'idTypeList': [[-1658759864, 'camouflage']]}]}]}]},
 10: {'name': 'UNIQUE_CREW_1_PLANE',
      'items': [{'type': 'add',
                 'idTypeList': [[0, 'slot']],
                 'count': 1,
                 'related': [{'type': 'add',
                              'idTypeList': [[1502, 'plane']],
                              'count': 1,
                              'related': [{'type': 'gift',
                                           'idTypeList': [[1, 'crewmember']],
                                           'count': 1}, {'type': 'gift',
                                           'idTypeList': [[None, 'crewmember'], [1502, 'plane']],
                                           'count': 1}]}]}]},
 11: {'name': 'UNIQUE_CREW_1',
      'items': [{'type': 'add',
                 'idTypeList': [[0, 'barrackslot']],
                 'count': 1,
                 'related': [{'type': 'gift',
                              'idTypeList': [[1, 'crewmember']],
                              'count': 1}]}]},
 12: {'name': 'UNIQUE_CREW_2_PLANE',
      'items': [{'type': 'add',
                 'idTypeList': [[0, 'slot']],
                 'count': 1,
                 'related': [{'type': 'add',
                              'idTypeList': [[2602, 'plane']],
                              'count': 1,
                              'related': [{'type': 'gift',
                                           'idTypeList': [[2, 'crewmember']],
                                           'count': 1}, {'type': 'gift',
                                           'idTypeList': [[None, 'crewmember'], [2602, 'plane']],
                                           'count': 1}]}]}]},
 13: {'name': 'UNIQUE_CREW_2',
      'items': [{'type': 'add',
                 'idTypeList': [[0, 'barrackslot']],
                 'count': 1,
                 'related': [{'type': 'gift',
                              'idTypeList': [[2, 'crewmember']],
                              'count': 1}]}]},
 14: {'name': 'UNIQUE_CREW_3_PLANE',
      'items': [{'type': 'add',
                 'idTypeList': [[0, 'slot']],
                 'count': 1,
                 'related': [{'type': 'add',
                              'idTypeList': [[3604, 'plane']],
                              'count': 1,
                              'related': [{'type': 'gift',
                                           'idTypeList': [[3, 'crewmember']],
                                           'count': 1}]}]}]},
 15: {'name': 'UNIQUE_CREW_3',
      'items': [{'type': 'add',
                 'idTypeList': [[0, 'barrackslot']],
                 'count': 1,
                 'related': [{'type': 'gift',
                              'idTypeList': [[3, 'crewmember']],
                              'count': 1}]}]}}