# Embedded file name: scripts/client/gui/HangarScripts/Hangar5Script.py
from NewYearHangarScript import NewYearHangarScript

class Hangar5Script(NewYearHangarScript):
    TIMELINES = [{'TIMERS': [(1, 2), (1, 3), (2, 4)],
      'POSITIONS': [(-116, 26, -40), (-182, 26, -25), (-153, 26, 24)],
      'PARTICLES': ['EFFECT_FIREWORKS_ALL',
                    'EFFECT_FIREWORKS_ALL_01',
                    'EFFECT_FIREWORKS_ALL_02',
                    'EFFECT_FIREWORKS_ALL_04',
                    'EFFECT_FIREWORKS_BLUE',
                    'EFFECT_FIREWORKS_BLUE_02',
                    'EFFECT_FIREWORKS_RED',
                    'EFFECT_FIREWORKS_RED_02',
                    'EFFECT_FIREWORKS_YELLOW',
                    'EFFECT_FIREWORKS_YELLOW_02']},
     {'TIMERS': [(1, 2), (1, 3), (2, 4)],
      'POSITIONS': [(-78, 26, 104),
                    (-32, 26, 156),
                    (-16, 26.4, 163.4),
                    (1.7, 32.8, 162.9)],
      'PARTICLES': ['EFFECT_FIREWORKS_ALL',
                    'EFFECT_FIREWORKS_ALL_01',
                    'EFFECT_FIREWORKS_ALL_02',
                    'EFFECT_FIREWORKS_ALL_04',
                    'EFFECT_FIREWORKS_BLUE',
                    'EFFECT_FIREWORKS_BLUE_02',
                    'EFFECT_FIREWORKS_RED',
                    'EFFECT_FIREWORKS_RED_02',
                    'EFFECT_FIREWORKS_YELLOW',
                    'EFFECT_FIREWORKS_YELLOW_02']},
     {'TIMERS': [(1, 2), (1, 3), (2, 4)],
      'POSITIONS': [(114, 15, -12), (121, 26, 29), (121, 20, -29)],
      'PARTICLES': ['EFFECT_FIREWORKS_ALL',
                    'EFFECT_FIREWORKS_ALL_01',
                    'EFFECT_FIREWORKS_ALL_02',
                    'EFFECT_FIREWORKS_ALL_04',
                    'EFFECT_FIREWORKS_BLUE',
                    'EFFECT_FIREWORKS_BLUE_02',
                    'EFFECT_FIREWORKS_RED',
                    'EFFECT_FIREWORKS_RED_02',
                    'EFFECT_FIREWORKS_YELLOW',
                    'EFFECT_FIREWORKS_YELLOW_02']},
     {'TIMERS': [(1, 2), (1, 3), (2, 4)],
      'POSITIONS': [(26, 8, -40), (40, 11, -40), (58, 13, -40)],
      'PARTICLES': ['EFFECT_FIREWORKS_ALL',
                    'EFFECT_FIREWORKS_ALL_01',
                    'EFFECT_FIREWORKS_ALL_02',
                    'EFFECT_FIREWORKS_ALL_04',
                    'EFFECT_FIREWORKS_BLUE',
                    'EFFECT_FIREWORKS_BLUE_02',
                    'EFFECT_FIREWORKS_RED',
                    'EFFECT_FIREWORKS_RED_02',
                    'EFFECT_FIREWORKS_YELLOW',
                    'EFFECT_FIREWORKS_YELLOW_02']},
     {'TIMERS': [(1, 2), (1, 3), (2, 4)],
      'POSITIONS': [(10, 18, -40), (0, 17, -40), (-13, 16, -40)],
      'PARTICLES': ['EFFECT_FIREWORKS_ALL',
                    'EFFECT_FIREWORKS_ALL_01',
                    'EFFECT_FIREWORKS_ALL_02',
                    'EFFECT_FIREWORKS_ALL_04',
                    'EFFECT_FIREWORKS_BLUE',
                    'EFFECT_FIREWORKS_BLUE_02',
                    'EFFECT_FIREWORKS_RED',
                    'EFFECT_FIREWORKS_RED_02',
                    'EFFECT_FIREWORKS_YELLOW',
                    'EFFECT_FIREWORKS_YELLOW_02']}]